### ISSUE TITLE
Basic Auth support

### ISSUE THREAD

**Issue by stringy05** [getsandbox/sandbox#1]
Hi 

I'd like sandbox to provide an out of the box Basic  Auth component so I can mock out my secured services as well. 

I've done this in js but it's a bit annoying since I need to apply the same function to every route, so I'm thinking it can have a bootstrap function on the API to setup and enforce basic auth - do the 401 challenge, check creds (or just the existence of them) and so on.

Cheers

Brock

**Comment by ntregillus** [comment]
Any movement on this? I have some issues with an integrator, and I want a simple place to show I can send basic auth header, and be recieved

**Comment by nhoughto** [comment]
No movement, other things have had focused. This is really around convenient support of things like basic auth, implementing basic auth is already do-able its just not as concise as possible. What is your use case? Actually validating the user/pass? or just validating that basic auth has been sent?

**Comment by ntregillus** [comment]
I found a workaround, by having the client implement preemptive basic auth. However, could you post a link to the workaround here?

**Comment by nhoughto** [comment]
If you are just trying to assert the Authorization header is set you could do this, if you actually want to valid the credentials you will need to get the header value, de-base64 it and write an assertion, not cover in the example but you can imagine how you would do it:

```javascript
Sandbox.define('/authed', 'get', function(req, res) {
    var allowed = false;
    if(req.headers.Authorization != undefined){
        //valid credentials here, decode base64, check user/pass.
        allowed = true   
    }
    
    if(allowed){
        res.send('Allowed');
    }else{
        res.send(403, 'Forbidden')
    }
});

**Comment by stringy05** [comment]
If you want to get a 401 with a challenge then try this

Sandbox.define('/authed', 'get', function(req, res) {
    var allowed = false;
    if(req.headers.Authorization != undefined){
        //valid credentials here, decode base64, check user/pass.
        allowed = true
    }

    if(allowed){
        res.send('Allowed');
    }else{

        res.set('WWW-Authenticate', 'Basic realm=sandbox');
        res.send(401, 'login')
    }
});

**Comment by nhoughto** [comment]
Closing as stale
