### ISSUE TITLE
Binary download link error 

### ISSUE THREAD

**Issue by matsinet** [getsandbox/sandbox#12]
When trying to access the binary download link (https://s3-us-west-2.amazonaws.com/sandbox-binaries/runtime-binary.tar) the following xml is displayed:
`<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>sandbox-binaries</Bucket><Endpoint>s3.amazonaws.com</Endpoint><RequestId>426167B0B8077CE4</RequestId><HostId>Oia1vLws6+gBbGY1qbIefnRU0u0GYsp5SB8+oMGEled1EySIn1BUjNUdqaqX1IvoL8YLB3MMWWA=</HostId></Error>`

**Comment by nhoughto** [comment]
Thanks, needed to drop the region prefix.

https://s3.amazonaws.com/sandbox-binaries/runtime-binary.tar
