### ISSUE TITLE
Adding a node module

### ISSUE THREAD

**Issue by elevenetc** [getsandbox/sandbox#14]
I need to add 'net' module into my mock server. But I get the error:

`com.sandbox.common.models.ServiceScriptException: Cannot find module: net in <sandbox-internal> at line number 243 at column number 6`

I install node module as usual, 'net' directory exists in `node_modules` and the module also defined in `package.json`. Is there some special requirements or limitation for usage node modules?

**Comment by nhoughto** [comment]
Hey

While we re-use the require() syntax that is common to node.js (and other JS environments), Sandbox does not run in node.js and thus doesn't support the node.js modules. Also we specifically have not built a 'net' or XMLHTTPRequest function that would allow outbound calls from Sandbox JS to somewhere else, as this would create an external dependency on your Sandbox execution which could / would be slow to execute. Our approach is that a Sandbox definition should contain (along with request data and state) all the information required to form the response.

The only scenario we've come across that is outside this is sending out of band data to another system, like OAuth. But depending on your environment and setup this can be accomplished with the use of state. What are you trying to achieve?

**Comment by elevenetc** [comment]
Hello, thanks for fast response.

We have a mobile application which sends requests to server and receives Push notifications from GCM. The app is heavily depends on GCM notifications.

And as we are using Sandbox as the mocked back-end we want to mock also GCM notifications. Thats why I need node net module: I'm planning to establish socket connection between Sandbox and mobile app, and trigger "push" notification by Sandbox.

**Comment by nhoughto** [comment]
That sounds like a valid user case, similar to the OAuth flow where out of band data needs to be sent upon receipt of request.

This _can_ be achieved indirectly at the moment through the Activity API, you would need to write a separate process (probably as part of your test case) that polls the Sandbox Activity API and fires off requests to GCM, rather than doing it through Sandbox itself.

Let me know if you want more info.

**Comment by elevenetc** [comment]
Thanks, but eventually we decided to switch from `Sandbox` to a simple node js server which responds to http requests and establishes tcp/socket connection.

**Comment by mstearne** [comment]
Also need support for npm modules. Even for prototyping building all libraries from scratch is difficult.

**Comment by alimoncul** [comment]
You can import minified version of module without libraries, only 1 js file
