### ISSUE TITLE
Route Builder UI

### ISSUE THREAD

**Issue by abhijeetahuja** [getsandbox/sandbox#15]
Can we have route builder UI running locally something like the UI for cloud and server plans? 
Excuse me if its already; Can you please let me know how to run it ?

**Comment by nhoughto** [comment]
Hey

So if you want a local server with a route builder UI, that is what the Sandbox Server is. Pricing is on the pricing page.

There is no support for a UI in the Sandbox Runtime, that is what the paid product is for.

**Comment by nhduong29** [comment]
Hi @abhijeetahuja ,

I'm implementing the feature that you can build the REST API or SOAP on the UI.
It's coming, Please keep in touch with me to get it soon 👍 
![image](https://user-images.githubusercontent.com/6943085/52099228-e548f800-2604-11e9-8698-e1b17be08d75.png)
