### ISSUE TITLE
OPTIONS requests returning Bad Request

### ISSUE THREAD

**Issue by jbernalvallejo** [getsandbox/sandbox#16]
When trying to perform CORS requests to getsandbox, OPTIONS requests are returning a 400 (Bad Request). 

The request is including usual CORS headers as Access-Control-Request-Headers or Access-Control-Request-Method but backend seems to be failing and consequent request are not performed.

**Comment by nhoughto** [comment]
CORS is supported, behaviour is to pass the Origin header back in the Allowed Origin header, CORS can fail for a number of tricky reasons, have you got more info about the failure from Chrome etc?

Quick test i just ran:

```
> curl http://query-test.getsandbox.com/users -H "Origin: blah.com" -v
*   Trying 107.170.234.83...
* Connected to query-test.getsandbox.com (107.170.234.83) port 80 (#0)
> GET /users HTTP/1.1
> Host: query-test.getsandbox.com
> User-Agent: curl/7.43.0
> Accept: */*
> Origin: blah.com
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
< Access-Control-Allow-Origin: blah.com
< Transfer-Encoding: chunked
< 
[
  {
    "name": "blah"
  }
]
> curl http://query-test.getsandbox.com/users -v
*   Trying 107.170.234.83...
* Connected to query-test.getsandbox.com (107.170.234.83) port 80 (#0)
> GET /users HTTP/1.1
> Host: query-test.getsandbox.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
< Access-Control-Allow-Origin: *
< Transfer-Encoding: chunked
< 
[
  {
    "name": "blah"
  }
```

**Comment by jbernalvallejo** [comment]
You are right. CORS requests are working fine and got it working using curl. 

I have spotted the problem though, derived from the framework I am using in my app to make the ajax requests. It is adding a slash at the end of the URL which is fine for my backend (.NET webAPI) but not for getsandbox (and therefore the 400 I was getting).

```
// fine for webapi, bad for 
http://query-test.getsandbox.com/organisations/?activeOnDate=2016-06-08 getsandbox
 // fine for both
http://query-test.getsandbox.com/organisations?activeOnDate=2016-06-08
```

I am not sure about how other frameworks or languages react when facing this situation.

**Comment by nhoughto** [comment]
You can support both (if you want to) by using a path parameter, a regex and just ignoring the value

```
Sandbox.define('/organisations{junk : .?}', function(req, res){
    res.send('works')
})
```

**Comment by jbernalvallejo** [comment]
Cool, thank you very much! You can close the issue. Cheers.
