### ISSUE TITLE
SOAP action field is ignored in sandbox runtime soap call

### ISSUE THREAD

**Issue by nilathj** [getsandbox/sandbox#19]
If I have defined a soap end point in main.js like:

Sandbox.soap("/Registrations-Registrations/DynamicFormsServiceV2", "", "setFields", Registrations_Registrations.SetFields);

This end point is not accessible when I call it with the action field "setFields" defined.  If I have the same end point without the action field, then it is called successfully.

**Comment by nhoughto** [comment]
Runtime does support SOAP calls, make sure you set your SOAPAction header if specified and ensure your SOAPOperationName matches the first element under the <soap:Body> tag.
