### ISSUE TITLE
Support for CORS

### ISSUE THREAD

**Issue by drewstewart** [getsandbox/sandbox#2]
CORS headers should be added to responses by default otherwise browsers sure have a hard time making requests.

**Comment by nhoughto** [comment]
Been done for ages.

**Comment by klh** [comment]
where and how was this implemented? getsandbox.com sure doesn't add a allow header to the output.,,

**Comment by drewstewart** [comment]
Hi Klaus,

Can you provide an example please? We replay "Origin" and "Access-Control-Request-Headers" from requests on responses.

**Comment by airtonix** [comment]
Where is the documetation around this behaviour?

**Comment by nhoughto** [comment]
Other than being a standard pattern, its not documented i don't think. Will put it on the doco backlog.
