### ISSUE TITLE
Build using Gradle

### ISSUE THREAD

**Issue by jenga201** [getsandbox/sandbox#21]
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.19.0-32-generic amd64

"gradle compileJava" outputs;
11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
**11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] **Could not determine the dependencies of task ':compileJava'.****
11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Configuration with name 'default' not found.
11:34:17.459 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:34:17.460 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
11:34:17.460 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
11:34:17.460 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
11:34:17.460 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
11:34:17.460 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
11:34:17.460 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 0.532 secs

What can I do to compile this properly?

**Comment by nhoughto** [comment]
Hey

Did you git clone and init submodules? Submodules are required to get everything..

**Comment by jenga201** [comment]
Yes, worked perfectly.
Thanks for your hint.

git submodule update --init --recursive
