### ISSUE TITLE
Verbose logging breaks output of soap+attachment

### ISSUE THREAD

**Issue by Kirjolohi** [getsandbox/sandbox#23]
Hi,

I ran into trouble while trying to mock a service that retuns soap+binary-attachment. Without running sandbox with flag --verbose it worked okay, but after enabling it I got the following error:

> java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 1; Content is not allowed in prolog.
> 	at com.sandbox.runtime.utils.FormatUtils.formatXml(FormatUtils.java:47) ~[sandbox:na]
> 	at com.sandbox.runtime.HttpRequestHandler.renderBody(HttpRequestHandler.java:216) ~[sandbox:na]
> 	at com.sandbox.runtime.HttpRequestHandler.logResponse(HttpRequestHandler.java:201) ~[sandbox:na]
> 	at com.sandbox.runtime.HttpRequestHandler.handle(HttpRequestHandler.java:155) ~[sandbox:na]
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [sandbox:na]
> 	at org.eclipse.jetty.server.Server.handle(Server.java:499) [sandbox:na]
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [sandbox:na]
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [sandbox:na]
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [sandbox:na]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [sandbox:na]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [sandbox:na]
> 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
> Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
> 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) ~[na:1.8.0_101]
> 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:1.8.0_101]
> 	at com.sandbox.runtime.utils.FormatUtils.formatXml(FormatUtils.java:32) ~[sandbox:na]
> 	... 11 common frames omitted
> 

I suppose this is related to my Content-Type header which is something like:  `Content-Type:` `multipart/related;start="9995-077";type="application/xop+xml";boundary="6d5ec";start-info="text/xml"` 

I think that the type=application/xop+xml breaks the logic because in file https://github.com/getsandbox/sandbox/blob/master/src/main/java/com/sandbox/runtime/utils/FormatUtils.java on line 21 there is a check: `headers.get("Content-Type").contains("xml"))` which would mean that the body is though to be xml, which is then tried to parse to xml, but in reality it's only partly.

**Comment by nhoughto** [comment]
Hmm interesting, will look into it.

**Comment by nhoughto** [comment]
Sorry it took so long, your comment is correct, invalid formatting logic is causing the problem, fix is pushed in 89cc1f4b7f27bf85e61e898abc1f6292ce7bff59
