### ISSUE TITLE
Are there any command to stop the runtime from command prompt?

### ISSUE THREAD

**Issue by pethirajan-apptium** [getsandbox/sandbox#24]
Like we have
java -jar A:/Workspace/sandbox-binary/sandbox --port=8081 --base=A:/Workspace/sandbox-binary/sandbox  run
Do we have any command  to stop this from command prompt?
If not what is the better approach to stop?

**Comment by nhoughto** [comment]
So the run command starts, and blocks until it is killed either via Ctrl-C or `kill` or whatever.

This approach suits process managers like upstart etc, where they can start and manage a process directly. Does Ctrl-C solve your problem?

**Comment by pethirajan-apptium** [comment]
My scenario goes like this...
I have to start/stop the sandbox through a java application, which I am able to do (I am have to place the sandbox in the file system to achieve this.. which is actually an another issue.. I will start another thread to discuss that). So after I start the sandbox through the java application I have to save the pid to kill the process tree, I feel this is not the right way to do. So are there any solution for such scenarios?
