### ISSUE TITLE
Route Param not parsing empty spaces or special characters. 

### ISSUE THREAD

**Issue by virgil-av** [getsandbox/sandbox#27]
Not sure if this is how it is supposed to work but sending req.params with spaces or special characters (Ex: | ) will not give the desired result.

**Comment by drewstewart** [comment]
Hey Avram, could you provide an example http request so I can test the behaviour please. thanks

**Comment by virgil-av** [comment]
I have sent the parsed url params to the console.log  and this is what you get: 

for: "auth|123456789"  you get auth%7C123456789
for: "auth 123456789"  get: auth%20123456789

Because of the browser converting spaces and special characters the params will  be equal to the transformed string not the original string, and you get no results after your query

I am not sure if this is normal behavior, this is the reason I have asked. Thank you.

Replicate
=====
You can use this route: 
**GET** /notes/{userid}

```
state.notes = state.notes || [];

var userId = req.params.userid;

var userNotes = _.filter(state.notes, {
    "id": userId
});

return res.json(userNotes);
```

**POST** http://ancient-feather-9941.getsandbox.com/notes

{
"id": "auth|123456789",
"content": "hi"
}

Use **GET** /notes/auth|123456789   // and you will get nothing in return same if you a space 

does not matter if you use _.filter, _.delete, _.find  the behavior is the same. 

But if your object looks like this: 

{
"id": "auth123456789",
"content": "hi"
}

Use **GET** /notes/auth123456789  //this will return the object


Below is the sandbox code
========

```
Sandbox.define('/notes','POST', function(req, res){
    if (!req.is("application/json")) {
        return res.send(400, "Invalid content type, expected application/json");
    };
    
    res.type("application/json");
    
    state.notes = state.notes || [];
   
    state.notes.push(req.body);
    
    return res.json(req.body);
})

Sandbox.define('/notes/{userid}','GET', function(req, res){

    state.notes = state.notes || [];
    
    var userId = req.params.userid;
    
    var userNotes = _.filter(state.notes, {
        "id": userId
    });
    
    return res.json(userNotes);
})
```

**Comment by drewstewart** [comment]
amazing detail, thanks for this. will look into it

**Comment by nhoughto** [comment]
So this works as expected with query params ?q=auth|1234 or ?q=auth%7C1234 both come out as auth|1234, but not with path params. Will need to check what the URI spec says about treatment of URI path segments and escaping..

**Comment by nhoughto** [comment]
Hey @virgil-av 

A fix for this has been rolled out in last nights release, path params are automatically unencoded before being passed to the route javascript, so your example will now receive 'auth|1234' rather than 'auth%7C1234'.
