### ISSUE TITLE
Support for OpenAPI v3.0

### ISSUE THREAD

**Issue by philsturgeon** [getsandbox/sandbox#31]
Hey folks, love the product! 

Is supporting OpenAPI v3.0 on the roadmap? Your upload seems to not mind me importing from v3.0, as there is no validation on `swagger: 2.0` in the file. It seems my `openapi: 3.0.1` file snuck by the upload, created all the URLs and methods, but just had an empty response, as the responses look like this now: 

``` yaml
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: foo
```

Do you think OpenAPI v3.0 support is something you'll be working on soon? It'd bring my company one step closer to being able to use this tool.

**Comment by nhoughto** [comment]
We do have v3 on the roadmap, seems like a number of groups are forming around it.

Any specific parts of v3 you are interested in seeing?

**Comment by philsturgeon** [comment]
Responses would be a quick and easy win for me, we could start using the product as soon as they were there. 

--
Phil Sturgeon
@philsturgeon

**Comment by nhoughto** [comment]
I'll get the team to investigate uplifting V2 to simple V3 support, from memory responses without schema based generation wasn't that hard.

**Comment by nhoughto** [comment]
Ah yeah schemas are a bit more tricky, we are somewhat constrained by wanting to support both on-premise and cloud hosted options, but we will have another look, from memory converting it first hadn't come up as an option last time we went down this path. Thanks for the info

**Comment by philsturgeon** [comment]
Hey @nhoughto, how's it coming along? I'm trying to implement a mock server at a hackathon currently, and I'm currently writing my own. I'd love to be a paying customer so I can delete this junk after. :D

**Comment by nhoughto** [comment]
Have been distracted sorry, there are other customers requesting openapi v3, so likely to get some focus soon. Its Top 5 at the moment =) Good luck with your hackathon.

**Comment by jormaechea** [comment]
Hey @nhoughto.. Has this reached Top 3 yet? :stuck_out_tongue_closed_eyes:

**Comment by nhoughto** [comment]
Thanks for the reminder, will go back to team and figure out if we can squeeze this in.

**Comment by ChrisHarrold** [comment]
Did this go anywhere? We have about 300 odd APIs in v3 spec that we would really like to mock from our readme.io docs and Sandbox seems like the way to go, BUT we cannot import our swagger specs. Would gladly pay for this if this feature existed...

**Comment by philsturgeon** [comment]
I got tired of waiting for companies to start offering OpenAPI v3.0 mocking so I joined Stoplight to help get Prism v3 out, and now it's in beta. https://github.com/stoplightio/prism/

Should help folks in here out, but I do hope this great tool can get OpenAPI v3.0 support soon too!

**Comment by nhoughto** [comment]
🤦‍♂ this has been too long, ill make sure it gets done this week.

**Comment by nhoughto** [comment]
@ChrisHarrold If you have some exotic examples already, maybe some of your 300. Could you send some to support@getsandbox.com and the team will take the patterns into consideration when building out the test cases etc.

**Comment by nhoughto** [comment]
This has just been pushed, so you can import v3 definitions now.
