### ISSUE TITLE
Sandbox is not saving response examples in .liquid templates

### ISSUE THREAD

**Issue by shilpa2112** [getsandbox/sandbox#33]
I have response examples defined as below for in open API spec
200:
         description: OK
         examples:
           application/json:
            "firstName": "testA"
            "lastName": "testB"
            "email": "testuser@test.com"
            "password": "test123"
            "phoneNumber" : "(121) 212-1212"
            "extension" : "222"
         But when this doc is imported in sandbox, response is not displayed in templates (.liquid)

**Comment by shilpa2112** [comment]
> Could you attach your import definition?


[middleware_ciam.json.zip](https://github.com/getsandbox/sandbox/files/2582580/middleware_ciam.json.zip)
Please find the attached definition.

**Comment by nhoughto** [comment]
So your response objects defined in the schema don't have examples (only some requests have examples), and the json schema defined for the response has a type of 'object', which means no schema effectively.

```
        "responses" : {
          "204" : {
            "description" : "Password successfully updated",
            "schema" : {
              "type" : "object"
            }
          },
```

You either need to define an example for the response(s) or define a proper json schema for the generated responses to function.
