### ISSUE TITLE
500 is returned when i call get 'https://bb8-api.getsandbox.com:443/hello'

### ISSUE THREAD

**Issue by arun290636** [getsandbox/sandbox#36]
Created a new get endpoint - https://bb8-api.getsandbox.com:443/hello
when i call this from browser/postman
500 is returned from getsandbox with below error message:
{
    "errors": [
        {
            "message": "Sorry, an error has occurred. Please check your request data and try again."
        }
    ]
}

**Comment by cesarfmacario** [comment]
Same issue

**Comment by nhoughto** [comment]
Service has been restored, sorry for the interruption. We expect to conduct our post mortem today.
