### ISSUE TITLE
Error with Latest compiled binary in OSX Mojave and JAVA

### ISSUE THREAD

**Issue by asos-albinotonnina** [getsandbox/sandbox#37]
with Java jdk-12.0.1_osx-x64_bin and also with jdk-8u211-macosx-x64

![image](https://user-images.githubusercontent.com/42975051/58958641-47745e00-879b-11e9-9560-eb8ab61ac0c9.png)

**Comment by nhoughto** [comment]
Ah yes probably due to the reflective access error, likely need a jvm arg to allow it.
Will investigate thanks

**Comment by nhoughto** [comment]
So reflective access would become a problem in the future, but the actual problem with JDK12 (of any variety not just OSX) is that nashorn is now been removed, we need nashorn for JavaScript execution and obviously it won't work without it.

Short term is to use JDK 11 and before. The future for JDK 12+ is to use GraalVM instead, which we are currently testing as per:

http://blog.getsandbox.com/2019/05/16/es10/
