### ISSUE TITLE
Runtime version 3 not supported

### ISSUE THREAD

**Issue by rafenden** [getsandbox/sandbox#44]
When trying to use version 3 of the runtime for es5 support I'm getting the following error message:

```
$ sandbox --runtimeVersion=VERSION_3 --watch=true --base=./test/sandbox run --port=8008
Invalid runtime version
```

According to the [docs](https://getsandbox.com/docs/js-libraries), runtime version 3 is supported.

**Comment by nhoughto** [comment]
`runtime` is being deprecated and replaced by a new `worker-cli` component. It isn't entirely released yet, but docker image is available here:

https://hub.docker.com/r/getsandbox/worker-cli

We expect to publish / deprecated etc this week.

**Comment by rafenden** [comment]
Thank you, just tested `worker-cli` and it seems that everything works fine with one exception, `GET` requests doesn't support body which was working in the old runtime.
