### ISSUE TITLE
[JS: Amanda] Error serialization

### ISSUE THREAD

**Issue by harnash** [getsandbox/sandbox#8]
I've noticed that when using Amanda for JSON Scheme validation I'm getting string as an error description instead of an object. I know this is due to some incompatibilities with nashorn but it's representation is somewhat hard to work with (please note the `property` and `message`):
```javascript
{
    "0": {
        "property": [
            0,
            "code"
        ],
        "propertyValue": "_n3Jt0IPGxHYuqH",
        "attributeName": "maxLength",
        "attributeValue": 10,
        "message": "The 0,code property must not exceed 10 characters. The length of the property is 15.",
        "validator": "maxLength",
        "validatorName": "maxLength",
        "validatorValue": 10
    },
    "length": 1,
    "errorMessages": {}
}
```
vs
```javascript
{
  '0': {
    property: 'users[0].username'
    propertyValue: 123
    attributeName: 'type'
    attributeValue: 'string',
    message: 'Lorem ipsum dolor isamet pide quidu delime.'
  },
  ...
}
``` 
from https://github.com/apiaryio/Amanda/blob/master/docs/json/objects/error.md. It is small nuisance but still :)

**Comment by nhoughto** [comment]
Yep, not sure why it was every like this. Fixed now. 

156aac8146bed1fcaa1d008605f0589d036418f1
