### ISSUE TITLE
Multiple execution of route methods

### ISSUE THREAD

**Issue by gorankl** [getsandbox/sandbox#9]
Hi, I've encountered this one both locally and on getsandbox.com:

Steps to reproduce:
Create new empty sandbox
In the first route add console.log i.e.

Sandbox.define('/hello', 'get', function(req, res) {
    console.log(1);
    res.send('Hello world');
});

When this route is executed for the first time, it prints 1 once, second time two time, etc.

It seems that the route method for the nth request is executed n times instead of only once.

Cheers,
Goran

**Comment by nhoughto** [comment]
Hey

Yep can replicate it, is an artifact of some optimizations we have recently done. Will fix.

**Comment by nhoughto** [comment]
Fixed

bf19c50ce4be23cabc5e6470251be43ae130a7d5
